app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='app/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('stock_add/<str:symbol>', views.StockAddView, name='stock_add'),
    path('stock_edit/<str:symbol>', views.StockEditView, name='stock_edit'),
    path('stock_delete/<str:symbol>', views.StockDeleteView, name='stock_delete'),
    path('search/',views.stock_search,name='stock_search'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView, name='index'),
    path('app/', include('app.urls')),
    path('app/', include('django.contrib.auth.urls')),
    path('dashboard/', views.DashboardView, name='dashboard'),
    path('logout_success/', views.LogoutSuccessView.as_view(), name='logout_success'),
]

app/templates/app/app_templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/master.css' %}">
        <script src="{% static 'js/master.js' %}"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
        <title>app</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #3f51b5;">
            <a class="navbar-brand mybrand" href="{% url 'index' %}"><i class="fab fa-gg" style="padding-right: 0.7rem; font-size: 3rem;"></i><b style="padding-bottom: 3rem; font-size: 3rem;">Investably</b></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'app:stock_search' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-search"></i> Search</button></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'dashboard' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-chart-line"></i> Dashboard</button></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'app:logout' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-sign-out-alt"></i> Sign Out</button></a></li>
                    <li class="nav-item user_text dashboard_username"><a class="nav-link">Hello, {{ user.username }}</a></li>

                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'app:login' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-sign-in-alt"></i> Sign In</button></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'app:signup' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-user-plus"></i> Register</button></a></li>
                {% endif %}
                </ul>
            </div>
      </nav>

      <div class="container">

        {% block content %}

        {% endblock %}

      </div>
    
    <script src="{% static 'js/master.js' %}"></script>

    </body>
</html>

app/templates/app/app_templates/dashboard.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}

        <br>
        <div class="container">
            <h3 class="display-4" style="padding-bottom: 0.5rem;">My portfolio</h3>
            <div class="container">
                <div class="row">
                    <table class="table table-bordered text-center table-hover">
                        <thead class="thead-light">
                          <tr>
                            <th>Symbol</th>
                            <th>Day Open</th>
                            <th>($)Price</th>
                            <th>Previous Close</th>
                            <th>Change Percent</th>
                            <th>Volume</th>
                            <th>($)Amount Invested</th>
                            <th>Operation</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for item in user_portfolio_stocks %}
                            <tr>
                                <td>{{ item.symbol }}</td>
                                <td>{{ item.day_open }}</td>
                                <td>{{ item.price }}</td>
                                <td>{{ item.previous_close }}</td>
                                <td>{{ item.change_percent }}</td>
                                <td>{{ item.volume }}</td>
                                <td>{{ item.get_amount }}</td>
                                <td>
                                    <a href="{% url 'app:stock_edit' symbol=item.symbol %}"><button type="button" class="btn btn-warning" style="width: 3rem;"><i class="fas fa-pencil-alt"></i></button></a>
                                    <a href="{% url 'app:stock_delete' symbol=item.symbol %}"><button type="button" class="btn btn-danger" style="width: 3rem;"><i class="far fa-trash-alt"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <br>
            <h3 class="display-4" style="padding-bottom: 0.5rem;">Top stocks</h3>
            <div class="container">
                <div class="row">
                    <table class="table table-bordered text-center table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th>Symbol</th>
                                <th>Name</th>
                                <th>($)Price</th>
                                <th>Dividend yield</th>
                                <th>Earning/Share</th>
                                <th>Operation</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for item in symbols %}
                            <tr>
                                <td>{{ item.symbol }}</td>
                                <td>{{ item.name }}</td>
                                <td>{{ item.price }}</td>
                                <td>{{ item.dividend_yield }}</td>
                                <td>{{ item.earning_share }}</td>
                                <td><a href="{% url 'app:stock_add' symbol=item.symbol %}"><button type="button" class="btn btn-primary" style="width: 6rem;"><i class="fas fa-plus-circle"></i></button></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <br>

    {% endblock %}

app/templates/app/app_templates/index.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}
    
        <br>
        <div class="container">
            <h3 class="display-3" style="padding-bottom: 0.5rem;">Stocks of popular companies</h3>
            <div class="container">
                <div class="row">
                    <div class="card mb-3 mx-auto" style="width: 100rem;">
                        <div class="card-body">
                            
                            <canvas id="line-chart" width="800" height="450"></canvas>
                            <script>
                                new Chart(document.getElementById("line-chart"), {
                                type: 'line',
                                data: {
                                  labels: [01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12],
                                  datasets: [{ 
                                      data: [39.4456, 19.4047, 5.0705, 9.5624, 16.3406, 18.2101, 26.0342, 19.2403, 16.4944, 3.5295, -6.1385, -5.3401],
                                      label: "Google",
                                      borderColor: "#3e95cd",
                                      fill: false
                                    }, { 
                                      data: [44.2606, 36.9705, 30.6844, 35.6739, 35.9560, 31.8844, 42.4084, 35.0445, 35.8798, 24.8656, 16.7140, 8.3182],
                                      label: "Microsoft",
                                      borderColor: "#8e5ea2",
                                      fill: false
                                    }, { 
                                      data: [82.8699, 91.4455, 81.1185, 109.1292, 93.5484, 124.0456, 86.0766, 87.1812, 99.4509, 57.2098, 5.8565, -8.1406],
                                      label: "Netflix",
                                      borderColor: "#3cba9f",
                                      fill: false
                                    }, { 
                                      data: [-5.9952, -2.7825, 0.5241, -5.7661, -2.3225, -2.3282, -0.1034, -4.9202, -1.7926, -24.7621, -24.0867, -27.0551],
                                      label: "IBM",
                                      borderColor: "#e8c3b9",
                                      fill: false
                                    }, { 
                                      data: [15.3561, 23.4733, 26.0022, 26.6198, 18.3723, 32.0586, 42.9245, 41.7716, 38.2850, 35.6653, 31.9626, 8.2749],
                                      label: "Motorola",
                                      borderColor: "#c45850",
                                      fill: false
                                    }
                                  ]
                                },
                                options: {
                                  title: {
                                    display: true,
                                    text: 'Rate of change v/s months of 2018'
                                  }
                                }
                            });
                            </script>

                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="card-deck">

                        <div class="card" style="height: 25rem; width: 42rem;">
                            <div class="card-header">
                                <h5 class="card-title display-5">Popular</h5>
                                <p class="card-text">Most popular funds</p>
                            </div>
                            <div class="card-body x6">
                                <ul class="list-group list-group-flush x4">
                                    <li class="list-group-item">Apple, Inc. (AAPL) ~ 38(+0%)</li>
                                    <li class="list-group-item">Apollo Group, Inc. (APOL) ~ 38(+1.05%)</li>
                                    <li class="list-group-item">MasterCard, Inc. (MA) ~ 22(+-1.82%)</li>
                                    <li class="list-group-item">BroadCom Corp. (BRCL) ~ 23(+-3.48%)</li>
                                    <li class="list-group-item">Gaiam, Inc. (GAIA) ~ 28(+0%)</li>
                                    <li class="list-group-item">Bebe Stores, Inc. (BEBE) ~ 22(+0.91%)</li>
                                    <li class="list-group-item">Ruthigen, Inc. (RTGN) ~ 0(+0%)</li>
                                </ul>
                            </div>
                        </div>

                        <div class="card" style="height: 25rem; width: 42rem;">
                            <div class="card-header">
                                <h5 class="card-title display-5">Gainers</h5>
                                <p class="card-text">Gaining funds</p>
                            </div>
                            <div class="card-body x6">
                                <ul class="list-group list-group-flush x5">
                                    <li class="list-group-item">TNT EXPRESS (TNTE.AS) ~ 4(+10%)</li>
                                    <li class="list-group-item">Vringo, Inc. (VRNG) ~ 2(+20%)</li>
                                    <li class="list-group-item">Walgreen Co. (WAG) ~ 4(10%)</li>
                                    <li class="list-group-item">Expedia, Inc. (EXPE) ~ 24(+5%)</li>
                                    <li class="list-group-item">LiveDeal, Inc. (LIVE) ~ 17(+4.17%)</li>
                                    <li class="list-group-item">Tiffany & Co. (TIF) ~ 19(+5.26%)</li>
                                    <li class="list-group-item">Fiat S.p.A (F.MI) ~ 23(+3.48%)</li>
                                </ul>
                            </div>
                        </div>

                        <div class="card" style="height: 25rem; width: 42rem;">
                            <div class="card-header">
                                <h5 class="card-title display-5">Losers</h5>
                                <p class="card-text">Losing funds</p>
                            </div>
                            <div class="card-body">
                                <ul class="list-group list-group-flush x6">
                                    <li class="list-group-item">DEXIA (DEXB>BI) ~ 2(+-10%)</li>
                                    <li class="list-group-item">Versartis, Inc. (VSAR) ~ 5(+-12%)</li>
                                    <li class="list-group-item">Ordina (ORDI>AS) ~ 14(+-4.29%)</li>
                                    <li class="list-group-item">TomTom NV (TOM2.AS) ~ 20(+-4%)</li>
                                    <li class="list-group-item">Daimlar AG (DAI.DE) ~ 21(+-4.76%)</li>
                                    <li class="list-group-item">Sprint Nextel Corp. (S) ~ 21(+-4.76%)</li>
                                    <li class="list-group-item">Mecom Group plc (MEC.L) ~ 10(+-6%)</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>

    {% endblock %}

app/templates/app/app_templates/login_success.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}

    {% block content %}

        <h1>logged in</h1>

    {% endblock %}

app/templates/app/app_templates/logout_success.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}

        <br>
        <br>
        <br>
        <div class="container">
            <div class="card mx-auto" style="width: 30rem;">
                <div class="card-header text-center">
                    <h1 class="my-auto" id="x5">Logged Out</h1>
                </div>
                <div class="card-body text-center">
                    <p class="x5 my-auto display-5">You have been succesfully logged out! <i class="far fa-smile"></i></p>
                    <p class="x5 my-auto"><a href="{% url 'app:login' %}">Visit again</a></p>
                </div>
            </div>
        </div>
        <br>

    {% endblock %}

app/templates/app/app_templates/search_results.html
{% extends 'app/app_templates/search_stocks.html' %}
    
    {% block hello %}

        <br>
        <div class="container">
            <h3 class="display-4" style="padding-bottom: 0.5rem;">Search results</h3>
            <div class="container">
                <div class="row">
                    <table class="table table-bordered text-center table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th>Symbol</th>
                                <th>Name</th>
                                <th>Operation</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for item in results %}
                            <tr>
                                <td>{{ item.symbol }}</td>
                                <td>{{ item.name }}</td>
                                <td><a href="{% url 'app:stock_add' symbol=item.symbol %}"><button type="button" class="btn btn-primary" style="width: 6rem;"><i class="fas fa-plus-circle"></i></button></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <br>

    {% endblock hello %}
        

app/templates/app/app_templates/search_stocks.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}

        <br>
<div class="container">
    <div class="card mx-auto" style="width: 50rem;">
        <div class="card-body">
            <form method="post">
            {% csrf_token %}
                <div class="row">
                  <div class="container">
                      <input type="text" class="form-control form-control-lg" name="symbol" placeholder="Type a stock symbol/name...">
                      <br>
                  </div>
                  <br>
                  <br>
                  <div class="container">
                      <button class="btn btn-success btn-block" type="submit">Search</button>
                  </div>
              </form>
        </div>
      </div>
    </div>
    <br>

        
        {% block hello %}
            
        {% endblock hello %}
            
    
    {% endblock %}

app/templates/app/app_templates/stock_delete.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}

    {% block content %}

        <h1>stock delete</h1>

    {% endblock %}

app/templates/app/app_templates/stock_detail.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

    {% block content %}

        <br>
        <div class="container">
            <h1 class="display-4" style="padding-bottom: 0.5rem;">Stock predictions</h1>
            <div class="container">
                <div class="row">
                    <div class="card mb-3 mx-auto" style="width: 100rem;">
                        <img class="card-img-top mx-auto" src={% static "images/"|add:symbol|add:".png" %} alt="OOPS" style="width: 55rem; padding-top: 0.5rem;">
                        <div class="card-body">
                            <h5 class="card-title display-5">Legend</h5>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><span style="color: #b71c1c; padding-right: 0.7rem;"><b>---------</b></span><b>Close</b> ~ Specifies the roc for closing prices of stocks</li>
                                <li class="list-group-item"><span style="color: blue; padding-right: 0.7rem;"><b>---------</b></span><b>Short Moving Average</b> ~ Responds quickly to the changes in the price of stocks</li>
                                <li class="list-group-item"><span style="color: #ffc107; padding-right: 0.7rem;"><b>---------</b></span><b>Long Moving Average</b> ~ Responds slowly to the changes in the price of stocks</li>
                                <li class="list-group-item"><span style="color: ; padding-right: 0.7rem;"><b><i class="fas fa-caret-up" style="color: yellow; padding-left:1rem;"></i></b></span><b style="padding-left: 2.2rem;">Buying Point</b> ~ Specifies the buying point for a particular stock</li>
                                <li class="list-group-item"><span style="color: ; padding-right: 0.7rem;"><b><i class="fas fa-caret-up" style="color: black; padding-left:1rem;"></i></b></span><b style="padding-left: 2.3rem;">Selling Point</b> ~ Specifies the selling point for a particular stock</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <h1 class="display-4" style="padding-bottom: 0.5rem;">Stock details</h1>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="card" style="height: 20rem;">
                            <div class="card-header">
                                <h5 class="card-title text-center">{{ symbol }}</h5>
                            </div>
                            <div class="card-body x6">
                                <ul class="list-group list-group-flush x4">
                                    <li class="list-group-item"><b>OPENED:</b> {{ opened }}</li>
                                    <li class="list-group-item"><b>HIGH:</b> {{ high }}</li>
                                    <li class="list-group-item"><b>LOW:</b> {{ low }}</li>
                                    <li class="list-group-item"><b>PRICE:</b>$ {{ price }}</li>
                                    <li class="list-group-item"><b>CHANGE PERCENT:</b> {{ change_percent }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="card" style="height: 20rem;">
                            <div class="card-header">
                                <h5 class="card-title text-center">{{ symbol }}</h5>
                            </div>
                            <div class="card-body">
                                <form method="post">
                                {% csrf_token %}
                                    <div class="form-group">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                        {% bootstrap_form form %}    
                                                </div>
                                                    <a href="{% url 'dashboard' %}"><button type="submit" class="btn btn-primary btn-lg" style="width: 29rem;">Submit</button></a>
                                            </div>
                                        </div>
                                    </div>    
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>


    {% endblock %}

app/templates/app/app_templates/stock_edit.html
{% extends 'app/app_templates/base.html' %}
{% load bootstrap4 %}

    {% block content %}

        <h1>stock edit form</h1>

    {% endblock %}